<?php
if ( !Mage::helper( 'core' )->isModuleEnabled( 'AnattaDesign_AbandonedCarts' ) ) {
	die();
}
?>

<link href='http://fonts.googleapis.com/css?family=Exo:600' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Exo:100' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Arvo' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Ubuntu:400,500' rel='stylesheet' type='text/css'>

<?php
$display_month = array(
	1 => 'January',
	2 => 'February',
	3 => 'March',
	4 => 'April',
	5 => 'May',
	6 => 'June',
	7 => 'July',
	8 => 'August',
	9 => 'September',
	10 => 'October',
	11 => 'November',
	12 => 'December'
);

$current_year = date( 'Y' );

if ( isset( $_GET['month'] ) && intval( abs( $_GET['month'] ) ) != 0 ) {
	$queried_month = intval( abs( $_GET['month'] ) );
} else {
	$queried_month = date( 'n' );
}

if ( isset( $_GET['year'] ) && intval( abs( $_GET['year'] ) ) != 0 ) {
	$queried_year = intval( abs( $_GET['year'] ) );
} else {
	$queried_year = $current_year;
}

// Select table name where data is stored
if ( Mage::helper( 'anattadesign_abandonedcarts' )->isAwesomeCheckoutActive() ) {

	$steps = array(
		0 => array(
			'step' => 'shipping'
		),
		1 => array(
			'step' => 'shipping_method'
		),
		2 => array(
			'step' => 'payment'
		),
		3 => array(
			'step' => 'review'
		)
	);
	$table = 'anattadesign_abandonedcarts_statistics';
} else {

	$steps = array(
		0 => array(
			'step' => 'login'
		),
		1 => array(
			'step' => 'billing'
		),
		2 => array(
			'step' => 'shipping'
		),
		3 => array(
			'step' => 'shipping_method'
		),
		4 => array(
			'step' => 'payment'
		),
		5 => array(
			'step' => 'review'
		)
	);

	$table = 'anattadesign_abandonedcarts_opstatistics';
}

// Add reached & moved values in array
$connection = Mage::getSingleton( 'core/resource' )->getConnection( 'core_read' );
foreach ( $steps as &$step ) {
	$query = "SELECT sum(reached) as reached, sum(moved) as moved FROM $table WHERE month = $queried_month AND year = $queried_year AND step = '" . $step['step'] . "';";
	$resource = $connection->query( $query );
	$fetched_data = $resource->fetch();
	$step['reached'] = intval( $fetched_data['reached'] );
	$step['moved'] = intval( $fetched_data['moved'] );
	$step['loss'] = $step['reached'] == $step['moved'] ? 0 : ( $step['reached'] - $step['moved'] ) * 100 / $step['reached'];
	unset( $step );
}

$step_no = 1;
$step_names = array(
	'login' => 'Login',
	'billing' => 'Billing',
	'shipping' => 'Shipping',
	'shipping_method' => 'Shipping Method',
	'payment' => 'Payment',
	'review' => 'Review'
);

// adjustments to data
if ( Mage::helper( 'anattadesign_abandonedcarts' )->isAwesomeCheckoutActive() ) {

} else {
	// make sure login[reached] is not smaller than billing[reached] (for the sake of funnel)
	$steps[0]['reached'] = max( $steps[0]['reached'], $steps[1]['reached'] );
	// make sure shipping step which is optional only depicts the loss, so add padding here (for the sake of funnel)
	$diff = $steps[1]['moved'] - $steps[2]['reached'];
	$steps[2]['reached']+= $diff;
	$steps[2]['moved']+= $diff;
}

// calculate abandonment rate & loss for the queried month-year
$abandonedment_rate = $steps[0]['reached'] == $steps[count( $steps ) - 1]['moved'] ? 0 : round( ( $steps[0]['reached'] - $steps[count( $steps ) - 1]['moved'] ) * 100 / $steps[0]['reached'], 2 );
$approx_loss = ( Mage::helper( 'anattadesign_abandonedcarts' )->getSalesVolume( $queried_year, $queried_month ) * ( $abandonedment_rate / 100 ) ) / ( 1 - ( $abandonedment_rate / 100 ) );
$approx_loss = Mage::helper( 'core' )->currency( $approx_loss, true, false );

// Get message to display user
$message = Mage::helper( 'anattadesign_abandonedcarts' )->getMessage();
?>

<div id="ac-wrapper">
	<!--header-->
	<header id="ac-header">
		<img class="left" src="<?php echo $this->getSkinUrl( 'anattadesign/abandonedcarts/css/images/logo.jpg' ); ?>" alt="Abandoned Cart"><!--logo-->
		<!--calender-->
		<div id="cal-widget" data-month="<?php echo $queried_month; ?>" data-year="<?php echo $queried_year; ?>" class="right">
			<a class="previous-month" href="#"></a>
			<span><?php echo $display_month[$queried_month] . ' ' . $queried_year; ?></span>
			<a class="next-month" href="#"></a>
		</div>
		<!--/calender-->
	</header>
	<!--/header-->
	<div id="ac-content">
		<?php if ( $steps[0]['reached'] == 0 ) { ?>
			<ul>
				<li><p class="out-of-data">You will see some data here as soon as we have it.</p></li>
			</ul>
		<?php } else { ?>
			<!--stats list-->
			<ul>
				<?php foreach ( $steps as $key => $step ) { ?>
					<li>
						<div class="ac-steps left"><span><?php echo $key + 1; ?>&nbsp;</span><?php echo $step_names[$step['step']]; ?></div>
						<div class="ac-graph left">
							<center><?php echo $step['reached']; ?></center>
							<div class="ac-usr-in" style="width:<?php echo $steps[0]['reached'] == 0 ? 0 : round( $step['reached'] * 100 / $steps[0]['reached'], 0 ); ?>px;">
								<div class="ac-usr-out" style="height:<?php echo round( $step['loss'], 0 ); ?>%"></div>
							</div>
							<?php
							// if on last step, show last 'moved' value i.e. tail of funnel
							if ( $key == count( $steps ) - 1 )
								echo '<center>' . $step['moved'] . '<center>';
							?>
						</div>
						<div class="ac-stats left"><div>&nbsp;<?php echo round( $step['loss'], 2 ); ?>&nbsp;%</div></div>
					</li>
				<?php } ?>
			</ul>
			<!--stats list-->
		<?php } ?>
		<!--sidebar-->
		<div id="ac-sidebar">
			<div class="ac-notif">
				<div>
					<big>NOTIFICATION!</big>
					<?php echo $message; ?>
				</div>
			</div>
			<div class="ac-side-content">
				<span>>APPX. LOSS</span>
				<p>*based on total monthly sales</p>
				<big><?php echo $approx_loss; ?></big>
				<p class="btm">TOTAL PERCENTAGE <br/>OF ABANDONMENT</p>
				<big class="btm"><?php echo $abandonedment_rate; ?>%</big>
			</div>
		</div>
		<!--sidebar-->
	</div>
</div>